# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway.proto',
  package='gateway',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rgateway.proto\x12\x07gateway\"\xa0\x01\n\x0cMenuResponse\x12&\n\nsandwiches\x18\x01 \x03(\x0b\x32\x12.gateway.Sandwiche\x12$\n\tdishMades\x18\x02 \x03(\x0b\x32\x11.gateway.DishMade\x12\x1e\n\x06\x64rinks\x18\x03 \x03(\x0b\x32\x0e.gateway.Drink\x12\"\n\x08\x64\x65sserts\x18\x04 \x03(\x0b\x32\x10.gateway.Dessert\"\"\n\x0bMenuRequest\x12\x13\n\x0btableNumber\x18\x01 \x01(\x05\"b\n\tSandwiche\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x17\n\x0fpreparationTime\x18\x04 \x01(\x03\x12\x13\n\x0bingredients\x18\x05 \x03(\t\"H\n\x08\x44ishMade\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x13\n\x0bingredients\x18\x04 \x03(\t\"0\n\x05\x44rink\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\"2\n\x07\x44\x65ssert\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\"/\n\x0cOrderRequest\x12\n\n\x02id\x18\x01 \x03(\t\x12\x13\n\x0btableNumber\x18\x02 \x01(\x05\"7\n\rOrderResponse\x12\r\n\x05\x66oods\x18\x01 \x03(\t\x12\x17\n\x0fpreparationTime\x18\x02 \x01(\x03\"*\n\x13\x43loseAccountRequest\x12\x13\n\x0btableNumber\x18\x01 \x01(\x05\"%\n\x14\x43loseAccountResponse\x12\r\n\x05total\x18\x01 \x01(\x01\x32\xd1\x01\n\x06Server\x12\x38\n\x07GetMenu\x12\x14.gateway.MenuRequest\x1a\x15.gateway.MenuResponse\"\x00\x12>\n\x0b\x43reateOrder\x12\x15.gateway.OrderRequest\x1a\x16.gateway.OrderResponse\"\x00\x12M\n\x0c\x43loseAccount\x12\x1c.gateway.CloseAccountRequest\x1a\x1d.gateway.CloseAccountResponse\"\x00\x62\x06proto3'
)




_MENURESPONSE = _descriptor.Descriptor(
  name='MenuResponse',
  full_name='gateway.MenuResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sandwiches', full_name='gateway.MenuResponse.sandwiches', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dishMades', full_name='gateway.MenuResponse.dishMades', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drinks', full_name='gateway.MenuResponse.drinks', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desserts', full_name='gateway.MenuResponse.desserts', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=187,
)


_MENUREQUEST = _descriptor.Descriptor(
  name='MenuRequest',
  full_name='gateway.MenuRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableNumber', full_name='gateway.MenuRequest.tableNumber', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=223,
)


_SANDWICHE = _descriptor.Descriptor(
  name='Sandwiche',
  full_name='gateway.Sandwiche',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gateway.Sandwiche.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='gateway.Sandwiche.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='gateway.Sandwiche.price', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preparationTime', full_name='gateway.Sandwiche.preparationTime', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ingredients', full_name='gateway.Sandwiche.ingredients', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=323,
)


_DISHMADE = _descriptor.Descriptor(
  name='DishMade',
  full_name='gateway.DishMade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gateway.DishMade.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='gateway.DishMade.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='gateway.DishMade.price', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ingredients', full_name='gateway.DishMade.ingredients', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=397,
)


_DRINK = _descriptor.Descriptor(
  name='Drink',
  full_name='gateway.Drink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gateway.Drink.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='gateway.Drink.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='gateway.Drink.price', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=447,
)


_DESSERT = _descriptor.Descriptor(
  name='Dessert',
  full_name='gateway.Dessert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gateway.Dessert.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='gateway.Dessert.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='gateway.Dessert.price', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=499,
)


_ORDERREQUEST = _descriptor.Descriptor(
  name='OrderRequest',
  full_name='gateway.OrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gateway.OrderRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tableNumber', full_name='gateway.OrderRequest.tableNumber', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=548,
)


_ORDERRESPONSE = _descriptor.Descriptor(
  name='OrderResponse',
  full_name='gateway.OrderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='foods', full_name='gateway.OrderResponse.foods', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preparationTime', full_name='gateway.OrderResponse.preparationTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=605,
)


_CLOSEACCOUNTREQUEST = _descriptor.Descriptor(
  name='CloseAccountRequest',
  full_name='gateway.CloseAccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableNumber', full_name='gateway.CloseAccountRequest.tableNumber', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=649,
)


_CLOSEACCOUNTRESPONSE = _descriptor.Descriptor(
  name='CloseAccountResponse',
  full_name='gateway.CloseAccountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='gateway.CloseAccountResponse.total', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=651,
  serialized_end=688,
)

_MENURESPONSE.fields_by_name['sandwiches'].message_type = _SANDWICHE
_MENURESPONSE.fields_by_name['dishMades'].message_type = _DISHMADE
_MENURESPONSE.fields_by_name['drinks'].message_type = _DRINK
_MENURESPONSE.fields_by_name['desserts'].message_type = _DESSERT
DESCRIPTOR.message_types_by_name['MenuResponse'] = _MENURESPONSE
DESCRIPTOR.message_types_by_name['MenuRequest'] = _MENUREQUEST
DESCRIPTOR.message_types_by_name['Sandwiche'] = _SANDWICHE
DESCRIPTOR.message_types_by_name['DishMade'] = _DISHMADE
DESCRIPTOR.message_types_by_name['Drink'] = _DRINK
DESCRIPTOR.message_types_by_name['Dessert'] = _DESSERT
DESCRIPTOR.message_types_by_name['OrderRequest'] = _ORDERREQUEST
DESCRIPTOR.message_types_by_name['OrderResponse'] = _ORDERRESPONSE
DESCRIPTOR.message_types_by_name['CloseAccountRequest'] = _CLOSEACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['CloseAccountResponse'] = _CLOSEACCOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MenuResponse = _reflection.GeneratedProtocolMessageType('MenuResponse', (_message.Message,), {
  'DESCRIPTOR' : _MENURESPONSE,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.MenuResponse)
  })
_sym_db.RegisterMessage(MenuResponse)

MenuRequest = _reflection.GeneratedProtocolMessageType('MenuRequest', (_message.Message,), {
  'DESCRIPTOR' : _MENUREQUEST,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.MenuRequest)
  })
_sym_db.RegisterMessage(MenuRequest)

Sandwiche = _reflection.GeneratedProtocolMessageType('Sandwiche', (_message.Message,), {
  'DESCRIPTOR' : _SANDWICHE,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.Sandwiche)
  })
_sym_db.RegisterMessage(Sandwiche)

DishMade = _reflection.GeneratedProtocolMessageType('DishMade', (_message.Message,), {
  'DESCRIPTOR' : _DISHMADE,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.DishMade)
  })
_sym_db.RegisterMessage(DishMade)

Drink = _reflection.GeneratedProtocolMessageType('Drink', (_message.Message,), {
  'DESCRIPTOR' : _DRINK,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.Drink)
  })
_sym_db.RegisterMessage(Drink)

Dessert = _reflection.GeneratedProtocolMessageType('Dessert', (_message.Message,), {
  'DESCRIPTOR' : _DESSERT,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.Dessert)
  })
_sym_db.RegisterMessage(Dessert)

OrderRequest = _reflection.GeneratedProtocolMessageType('OrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREQUEST,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.OrderRequest)
  })
_sym_db.RegisterMessage(OrderRequest)

OrderResponse = _reflection.GeneratedProtocolMessageType('OrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _ORDERRESPONSE,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.OrderResponse)
  })
_sym_db.RegisterMessage(OrderResponse)

CloseAccountRequest = _reflection.GeneratedProtocolMessageType('CloseAccountRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEACCOUNTREQUEST,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.CloseAccountRequest)
  })
_sym_db.RegisterMessage(CloseAccountRequest)

CloseAccountResponse = _reflection.GeneratedProtocolMessageType('CloseAccountResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEACCOUNTRESPONSE,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.CloseAccountResponse)
  })
_sym_db.RegisterMessage(CloseAccountResponse)



_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='gateway.Server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=691,
  serialized_end=900,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMenu',
    full_name='gateway.Server.GetMenu',
    index=0,
    containing_service=None,
    input_type=_MENUREQUEST,
    output_type=_MENURESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateOrder',
    full_name='gateway.Server.CreateOrder',
    index=1,
    containing_service=None,
    input_type=_ORDERREQUEST,
    output_type=_ORDERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CloseAccount',
    full_name='gateway.Server.CloseAccount',
    index=2,
    containing_service=None,
    input_type=_CLOSEACCOUNTREQUEST,
    output_type=_CLOSEACCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
