# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service-dish-made.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service-dish-made.proto',
  package='dishMadeService',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17service-dish-made.proto\x12\x0f\x64ishMadeService\"a\n\x08\x44ishMade\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x17\n\x0fpreparationTime\x18\x04 \x01(\x03\x12\x13\n\x0bingredients\x18\x05 \x03(\t\"D\n\x14\x46indDishMadeResponse\x12,\n\tdishMades\x18\x01 \x03(\x0b\x32\x19.dishMadeService.DishMade\"*\n\x13\x46indDishMadeRequest\x12\x13\n\x0btableNumber\x18\x01 \x01(\x05\x32q\n\x0f\x44ishMadeService\x12^\n\rFindDishMades\x12$.dishMadeService.FindDishMadeRequest\x1a%.dishMadeService.FindDishMadeResponse\"\x00\x62\x06proto3'
)




_DISHMADE = _descriptor.Descriptor(
  name='DishMade',
  full_name='dishMadeService.DishMade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dishMadeService.DishMade.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='dishMadeService.DishMade.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='dishMadeService.DishMade.price', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preparationTime', full_name='dishMadeService.DishMade.preparationTime', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ingredients', full_name='dishMadeService.DishMade.ingredients', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=141,
)


_FINDDISHMADERESPONSE = _descriptor.Descriptor(
  name='FindDishMadeResponse',
  full_name='dishMadeService.FindDishMadeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dishMades', full_name='dishMadeService.FindDishMadeResponse.dishMades', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=211,
)


_FINDDISHMADEREQUEST = _descriptor.Descriptor(
  name='FindDishMadeRequest',
  full_name='dishMadeService.FindDishMadeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableNumber', full_name='dishMadeService.FindDishMadeRequest.tableNumber', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=255,
)

_FINDDISHMADERESPONSE.fields_by_name['dishMades'].message_type = _DISHMADE
DESCRIPTOR.message_types_by_name['DishMade'] = _DISHMADE
DESCRIPTOR.message_types_by_name['FindDishMadeResponse'] = _FINDDISHMADERESPONSE
DESCRIPTOR.message_types_by_name['FindDishMadeRequest'] = _FINDDISHMADEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DishMade = _reflection.GeneratedProtocolMessageType('DishMade', (_message.Message,), {
  'DESCRIPTOR' : _DISHMADE,
  '__module__' : 'service_dish_made_pb2'
  # @@protoc_insertion_point(class_scope:dishMadeService.DishMade)
  })
_sym_db.RegisterMessage(DishMade)

FindDishMadeResponse = _reflection.GeneratedProtocolMessageType('FindDishMadeResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINDDISHMADERESPONSE,
  '__module__' : 'service_dish_made_pb2'
  # @@protoc_insertion_point(class_scope:dishMadeService.FindDishMadeResponse)
  })
_sym_db.RegisterMessage(FindDishMadeResponse)

FindDishMadeRequest = _reflection.GeneratedProtocolMessageType('FindDishMadeRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDDISHMADEREQUEST,
  '__module__' : 'service_dish_made_pb2'
  # @@protoc_insertion_point(class_scope:dishMadeService.FindDishMadeRequest)
  })
_sym_db.RegisterMessage(FindDishMadeRequest)



_DISHMADESERVICE = _descriptor.ServiceDescriptor(
  name='DishMadeService',
  full_name='dishMadeService.DishMadeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=257,
  serialized_end=370,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindDishMades',
    full_name='dishMadeService.DishMadeService.FindDishMades',
    index=0,
    containing_service=None,
    input_type=_FINDDISHMADEREQUEST,
    output_type=_FINDDISHMADERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISHMADESERVICE)

DESCRIPTOR.services_by_name['DishMadeService'] = _DISHMADESERVICE

# @@protoc_insertion_point(module_scope)
