# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service-dessert.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service-dessert.proto',
  package='dessertService',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15service-dessert.proto\x12\x0e\x64\x65ssertService\"2\n\x07\x44\x65ssert\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\"@\n\x13\x46indDessertResponse\x12)\n\x08\x64\x65sserts\x18\x01 \x03(\x0b\x32\x17.dessertService.Dessert\")\n\x12\x46indDessertRequest\x12\x13\n\x0btableNumber\x18\x01 \x01(\x05\x32k\n\x0e\x44\x65ssertService\x12Y\n\x0c\x46indDesserts\x12\".dessertService.FindDessertRequest\x1a#.dessertService.FindDessertResponse\"\x00\x62\x06proto3'
)




_DESSERT = _descriptor.Descriptor(
  name='Dessert',
  full_name='dessertService.Dessert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dessertService.Dessert.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='dessertService.Dessert.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='dessertService.Dessert.price', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=91,
)


_FINDDESSERTRESPONSE = _descriptor.Descriptor(
  name='FindDessertResponse',
  full_name='dessertService.FindDessertResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='desserts', full_name='dessertService.FindDessertResponse.desserts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=157,
)


_FINDDESSERTREQUEST = _descriptor.Descriptor(
  name='FindDessertRequest',
  full_name='dessertService.FindDessertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableNumber', full_name='dessertService.FindDessertRequest.tableNumber', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=200,
)

_FINDDESSERTRESPONSE.fields_by_name['desserts'].message_type = _DESSERT
DESCRIPTOR.message_types_by_name['Dessert'] = _DESSERT
DESCRIPTOR.message_types_by_name['FindDessertResponse'] = _FINDDESSERTRESPONSE
DESCRIPTOR.message_types_by_name['FindDessertRequest'] = _FINDDESSERTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dessert = _reflection.GeneratedProtocolMessageType('Dessert', (_message.Message,), {
  'DESCRIPTOR' : _DESSERT,
  '__module__' : 'service_dessert_pb2'
  # @@protoc_insertion_point(class_scope:dessertService.Dessert)
  })
_sym_db.RegisterMessage(Dessert)

FindDessertResponse = _reflection.GeneratedProtocolMessageType('FindDessertResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINDDESSERTRESPONSE,
  '__module__' : 'service_dessert_pb2'
  # @@protoc_insertion_point(class_scope:dessertService.FindDessertResponse)
  })
_sym_db.RegisterMessage(FindDessertResponse)

FindDessertRequest = _reflection.GeneratedProtocolMessageType('FindDessertRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDDESSERTREQUEST,
  '__module__' : 'service_dessert_pb2'
  # @@protoc_insertion_point(class_scope:dessertService.FindDessertRequest)
  })
_sym_db.RegisterMessage(FindDessertRequest)



_DESSERTSERVICE = _descriptor.ServiceDescriptor(
  name='DessertService',
  full_name='dessertService.DessertService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=202,
  serialized_end=309,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindDesserts',
    full_name='dessertService.DessertService.FindDesserts',
    index=0,
    containing_service=None,
    input_type=_FINDDESSERTREQUEST,
    output_type=_FINDDESSERTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DESSERTSERVICE)

DESCRIPTOR.services_by_name['DessertService'] = _DESSERTSERVICE

# @@protoc_insertion_point(module_scope)
