# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service-sandwiche.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service-sandwiche.proto',
  package='service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17service-sandwiche.proto\x12\x07service\"b\n\tSandwiche\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x17\n\x0fpreparationTime\x18\x04 \x01(\x03\x12\x13\n\x0bingredients\x18\x05 \x03(\t\"@\n\x16\x46indSandwichesResponse\x12&\n\nsandwiches\x18\x01 \x03(\x0b\x32\x12.service.Sandwiche\",\n\x15\x46indSandwichesRequest\x12\x13\n\x0btableNumber\x18\x01 \x01(\x05\x32g\n\x10SandwicheService\x12S\n\x0e\x46indSandwiches\x12\x1e.service.FindSandwichesRequest\x1a\x1f.service.FindSandwichesResponse\"\x00\x62\x06proto3'
)




_SANDWICHE = _descriptor.Descriptor(
  name='Sandwiche',
  full_name='service.Sandwiche',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='service.Sandwiche.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='service.Sandwiche.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='service.Sandwiche.price', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preparationTime', full_name='service.Sandwiche.preparationTime', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ingredients', full_name='service.Sandwiche.ingredients', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=134,
)


_FINDSANDWICHESRESPONSE = _descriptor.Descriptor(
  name='FindSandwichesResponse',
  full_name='service.FindSandwichesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sandwiches', full_name='service.FindSandwichesResponse.sandwiches', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=200,
)


_FINDSANDWICHESREQUEST = _descriptor.Descriptor(
  name='FindSandwichesRequest',
  full_name='service.FindSandwichesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableNumber', full_name='service.FindSandwichesRequest.tableNumber', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=246,
)

_FINDSANDWICHESRESPONSE.fields_by_name['sandwiches'].message_type = _SANDWICHE
DESCRIPTOR.message_types_by_name['Sandwiche'] = _SANDWICHE
DESCRIPTOR.message_types_by_name['FindSandwichesResponse'] = _FINDSANDWICHESRESPONSE
DESCRIPTOR.message_types_by_name['FindSandwichesRequest'] = _FINDSANDWICHESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sandwiche = _reflection.GeneratedProtocolMessageType('Sandwiche', (_message.Message,), {
  'DESCRIPTOR' : _SANDWICHE,
  '__module__' : 'service_sandwiche_pb2'
  # @@protoc_insertion_point(class_scope:service.Sandwiche)
  })
_sym_db.RegisterMessage(Sandwiche)

FindSandwichesResponse = _reflection.GeneratedProtocolMessageType('FindSandwichesResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINDSANDWICHESRESPONSE,
  '__module__' : 'service_sandwiche_pb2'
  # @@protoc_insertion_point(class_scope:service.FindSandwichesResponse)
  })
_sym_db.RegisterMessage(FindSandwichesResponse)

FindSandwichesRequest = _reflection.GeneratedProtocolMessageType('FindSandwichesRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDSANDWICHESREQUEST,
  '__module__' : 'service_sandwiche_pb2'
  # @@protoc_insertion_point(class_scope:service.FindSandwichesRequest)
  })
_sym_db.RegisterMessage(FindSandwichesRequest)



_SANDWICHESERVICE = _descriptor.ServiceDescriptor(
  name='SandwicheService',
  full_name='service.SandwicheService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=248,
  serialized_end=351,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindSandwiches',
    full_name='service.SandwicheService.FindSandwiches',
    index=0,
    containing_service=None,
    input_type=_FINDSANDWICHESREQUEST,
    output_type=_FINDSANDWICHESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SANDWICHESERVICE)

DESCRIPTOR.services_by_name['SandwicheService'] = _SANDWICHESERVICE

# @@protoc_insertion_point(module_scope)
